// Comprehensive list of Indian colleges with codes
// Includes national institutes, state colleges, and Bihar engineering colleges

export interface College {
    name: string;
    code: string;
    state: string;
    category: 'national' | 'state' | 'bihar-engineering';
}

export const COLLEGES: College[] = [
    // ── National Institutes (IITs) ───────────────────────────────────────
    { name: 'IIT Bombay', code: 'IITB', state: 'Maharashtra', category: 'national' },
    { name: 'IIT Delhi', code: 'IITD', state: 'Delhi', category: 'national' },
    { name: 'IIT Madras', code: 'IITM', state: 'Tamil Nadu', category: 'national' },
    { name: 'IIT Kanpur', code: 'IITK', state: 'Uttar Pradesh', category: 'national' },
    { name: 'IIT Kharagpur', code: 'IITKGP', state: 'West Bengal', category: 'national' },
    { name: 'IIT Roorkee', code: 'IITR', state: 'Uttarakhand', category: 'national' },
    { name: 'IIT Guwahati', code: 'IITG', state: 'Assam', category: 'national' },
    { name: 'IIT Hyderabad', code: 'IITH', state: 'Telangana', category: 'national' },
    { name: 'IIT BHU Varanasi', code: 'IITBHU', state: 'Uttar Pradesh', category: 'national' },
    { name: 'IIT Gandhinagar', code: 'IITGN', state: 'Gujarat', category: 'national' },
    { name: 'IIT Ropar', code: 'IITRPR', state: 'Punjab', category: 'national' },
    { name: 'IIT Bhubaneswar', code: 'IITBBS', state: 'Odisha', category: 'national' },
    { name: 'IIT Mandi', code: 'IITMandi', state: 'Himachal Pradesh', category: 'national' },
    { name: 'IIT Patna', code: 'IITP', state: 'Bihar', category: 'national' },
    { name: 'IIT Indore', code: 'IITI', state: 'Madhya Pradesh', category: 'national' },
    { name: 'IIT Jodhpur', code: 'IITJ', state: 'Rajasthan', category: 'national' },
    { name: 'IIT Tirupati', code: 'IITT', state: 'Andhra Pradesh', category: 'national' },
    { name: 'IIT Palakkad', code: 'IITPKD', state: 'Kerala', category: 'national' },
    { name: 'IIT (ISM) Dhanbad', code: 'IITISM', state: 'Jharkhand', category: 'national' },
    { name: 'IIT Goa', code: 'IITGoa', state: 'Goa', category: 'national' },
    { name: 'IIT Jammu', code: 'IITJMU', state: 'Jammu & Kashmir', category: 'national' },
    { name: 'IIT Dharwad', code: 'IITDH', state: 'Karnataka', category: 'national' },
    { name: 'IIT Bhilai', code: 'IITBH', state: 'Chhattisgarh', category: 'national' },

    // ── National Institutes (NITs) ───────────────────────────────────────
    { name: 'NIT Trichy', code: 'NITT', state: 'Tamil Nadu', category: 'national' },
    { name: 'NIT Surathkal', code: 'NITK', state: 'Karnataka', category: 'national' },
    { name: 'NIT Warangal', code: 'NITW', state: 'Telangana', category: 'national' },
    { name: 'NIT Calicut', code: 'NITC', state: 'Kerala', category: 'national' },
    { name: 'NIT Durgapur', code: 'NITDGP', state: 'West Bengal', category: 'national' },
    { name: 'NIT Rourkela', code: 'NITRKL', state: 'Odisha', category: 'national' },
    { name: 'NIT Kurukshetra', code: 'NITKKR', state: 'Haryana', category: 'national' },
    { name: 'NIT Patna', code: 'NITP', state: 'Bihar', category: 'national' },
    { name: 'NIT Silchar', code: 'NITS', state: 'Assam', category: 'national' },
    { name: 'NIT Hamirpur', code: 'NITH', state: 'Himachal Pradesh', category: 'national' },
    { name: 'NIT Jalandhar', code: 'NITJ', state: 'Punjab', category: 'national' },
    { name: 'NIT Raipur', code: 'NITRR', state: 'Chhattisgarh', category: 'national' },
    { name: 'NIT Agartala', code: 'NITA', state: 'Tripura', category: 'national' },
    { name: 'NIT Srinagar', code: 'NITSRI', state: 'Jammu & Kashmir', category: 'national' },
    { name: 'NIT Jamshedpur', code: 'NITJSR', state: 'Jharkhand', category: 'national' },
    { name: 'VNIT Nagpur', code: 'VNIT', state: 'Maharashtra', category: 'national' },
    { name: 'MNNIT Allahabad', code: 'MNNIT', state: 'Uttar Pradesh', category: 'national' },
    { name: 'MANIT Bhopal', code: 'MANIT', state: 'Madhya Pradesh', category: 'national' },
    { name: 'MNIT Jaipur', code: 'MNIT', state: 'Rajasthan', category: 'national' },
    { name: 'NIT Meghalaya', code: 'NITM', state: 'Meghalaya', category: 'national' },
    { name: 'NIT Mizoram', code: 'NITMZ', state: 'Mizoram', category: 'national' },
    { name: 'NIT Nagaland', code: 'NITNL', state: 'Nagaland', category: 'national' },
    { name: 'NIT Manipur', code: 'NITMN', state: 'Manipur', category: 'national' },
    { name: 'NIT Arunachal Pradesh', code: 'NITAP', state: 'Arunachal Pradesh', category: 'national' },
    { name: 'NIT Sikkim', code: 'NITSKM', state: 'Sikkim', category: 'national' },
    { name: 'NIT Uttarakhand', code: 'NITUK', state: 'Uttarakhand', category: 'national' },
    { name: 'NIT Goa', code: 'NITGOA', state: 'Goa', category: 'national' },
    { name: 'NIT Delhi', code: 'NITDL', state: 'Delhi', category: 'national' },
    { name: 'NIT Puducherry', code: 'NITPY', state: 'Puducherry', category: 'national' },
    { name: 'NIT Andhra Pradesh', code: 'NITANP', state: 'Andhra Pradesh', category: 'national' },

    // ── National Institutes (IIITs) ──────────────────────────────────────
    { name: 'IIIT Hyderabad', code: 'IIITH', state: 'Telangana', category: 'national' },
    { name: 'IIIT Delhi', code: 'IIITD', state: 'Delhi', category: 'national' },
    { name: 'IIIT Bangalore', code: 'IIITB', state: 'Karnataka', category: 'national' },
    { name: 'IIIT Allahabad', code: 'IIITA', state: 'Uttar Pradesh', category: 'national' },
    { name: 'IIIT Guwahati', code: 'IIITG', state: 'Assam', category: 'national' },
    { name: 'IIIT Jabalpur', code: 'IIITJ', state: 'Madhya Pradesh', category: 'national' },
    { name: 'IIIT Kancheepuram', code: 'IIITK', state: 'Tamil Nadu', category: 'national' },
    { name: 'IIIT Kottayam', code: 'IIITKTM', state: 'Kerala', category: 'national' },
    { name: 'IIIT Manipur', code: 'IIITMN', state: 'Manipur', category: 'national' },
    { name: 'IIIT Nagpur', code: 'IIITN', state: 'Maharashtra', category: 'national' },
    { name: 'IIIT Pune', code: 'IIITP', state: 'Maharashtra', category: 'national' },
    { name: 'IIIT Ranchi', code: 'IIITR', state: 'Jharkhand', category: 'national' },
    { name: 'IIIT Sri City', code: 'IIITS', state: 'Andhra Pradesh', category: 'national' },
    { name: 'IIIT Surat', code: 'IIITSUR', state: 'Gujarat', category: 'national' },
    { name: 'IIIT Una', code: 'IIITU', state: 'Himachal Pradesh', category: 'national' },
    { name: 'IIIT Vadodara', code: 'IIITV', state: 'Gujarat', category: 'national' },
    { name: 'IIIT Bhagalpur', code: 'IIITBGP', state: 'Bihar', category: 'national' },
    { name: 'IIIT Bhopal', code: 'IIITBPL', state: 'Madhya Pradesh', category: 'national' },
    { name: 'IIIT Dharwad', code: 'IIITDHW', state: 'Karnataka', category: 'national' },
    { name: 'IIIT Kota', code: 'IIITKOTA', state: 'Rajasthan', category: 'national' },
    { name: 'IIIT Lucknow', code: 'IIITLKO', state: 'Uttar Pradesh', category: 'national' },
    { name: 'IIIT Sonepat', code: 'IIITSNP', state: 'Haryana', category: 'national' },

    // ── Other National Institutes ────────────────────────────────────────
    { name: 'IISc Bangalore', code: 'IISc', state: 'Karnataka', category: 'national' },
    { name: 'Indian Statistical Institute Kolkata', code: 'ISI', state: 'West Bengal', category: 'national' },
    { name: 'AIIMS Delhi', code: 'AIIMS', state: 'Delhi', category: 'national' },
    { name: 'NIFT Delhi', code: 'NIFT', state: 'Delhi', category: 'national' },
    { name: 'NLSIU Bangalore', code: 'NLSIU', state: 'Karnataka', category: 'national' },
    { name: 'ISB Hyderabad', code: 'ISB', state: 'Telangana', category: 'national' },
    { name: 'IIM Ahmedabad', code: 'IIMA', state: 'Gujarat', category: 'national' },
    { name: 'IIM Bangalore', code: 'IIMB', state: 'Karnataka', category: 'national' },
    { name: 'IIM Calcutta', code: 'IIMC', state: 'West Bengal', category: 'national' },
    { name: 'IIM Lucknow', code: 'IIML', state: 'Uttar Pradesh', category: 'national' },
    { name: 'IIM Kozhikode', code: 'IIMK', state: 'Kerala', category: 'national' },
    { name: 'IIM Indore', code: 'IIMI', state: 'Madhya Pradesh', category: 'national' },
    { name: 'IIM Rohtak', code: 'IIMR', state: 'Haryana', category: 'national' },
    { name: 'IIM Ranchi', code: 'IIMRAN', state: 'Jharkhand', category: 'national' },
    { name: 'IIM Raipur', code: 'IIMRPR', state: 'Chhattisgarh', category: 'national' },
    { name: 'IIM Tiruchirappalli', code: 'IIMT', state: 'Tamil Nadu', category: 'national' },
    { name: 'IIM Udaipur', code: 'IIMU', state: 'Rajasthan', category: 'national' },
    { name: 'IIM Kashipur', code: 'IIMKAS', state: 'Uttarakhand', category: 'national' },
    { name: 'IIM Bodh Gaya', code: 'IIMBG', state: 'Bihar', category: 'national' },
    { name: 'IIM Visakhapatnam', code: 'IIMV', state: 'Andhra Pradesh', category: 'national' },
    { name: 'IIM Nagpur', code: 'IIMNGP', state: 'Maharashtra', category: 'national' },
    { name: 'IIM Amritsar', code: 'IIMASR', state: 'Punjab', category: 'national' },
    { name: 'IIM Sambalpur', code: 'IIMSBP', state: 'Odisha', category: 'national' },
    { name: 'IIM Sirmaur', code: 'IIMSMR', state: 'Himachal Pradesh', category: 'national' },
    { name: 'IIM Jammu', code: 'IIMJMU', state: 'Jammu & Kashmir', category: 'national' },
    { name: 'IIM Shillong', code: 'IIMSHL', state: 'Meghalaya', category: 'national' },
    { name: 'IIM Mumbai', code: 'IIMM', state: 'Maharashtra', category: 'national' },

    // ── Bihar Engineering Colleges (BEU Affiliated) ──────────────────────
    { name: 'Bihar Engineering University (BEU) Patna', code: 'BEU', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Muzaffarpur Institute of Technology', code: 'MIT', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Bhagalpur College of Engineering', code: 'BCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Gaya College of Engineering', code: 'GCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Darbhanga College of Engineering', code: 'DCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Motihari College of Engineering', code: 'MCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Nalanda College of Engineering', code: 'NCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Purnea College of Engineering', code: 'PCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Saharsa College of Engineering', code: 'SCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Sitamarhi Institute of Technology', code: 'SIT', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'Bakhtiyarpur College of Engineering', code: 'BKCE', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Vaishali', code: 'GECV', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Banka', code: 'GECB', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Jamui', code: 'GECJ', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Sheikhpura', code: 'GECS', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Arwal', code: 'GECA', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Buxar', code: 'GECBX', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Aurangabad', code: 'GECAB', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Nawada', code: 'GECN', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Rohtas', code: 'GECR', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Bhojpur', code: 'GECBJ', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Madhubani', code: 'GECMD', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Samastipur', code: 'GECSM', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Supaul', code: 'GECSP', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Khagaria', code: 'GECKH', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Lakhisarai', code: 'GECLK', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Begusarai', code: 'GECBG', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Munger', code: 'GECMG', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Gopalganj', code: 'GECGP', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Siwan', code: 'GECSW', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Saran', code: 'GECSR', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Kaimur', code: 'GECKM', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Jehanabad', code: 'GECJH', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Kishanganj', code: 'GECKG', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Araria', code: 'GECAR', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Katihar', code: 'GECKT', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC West Champaran', code: 'GECWC', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC East Champaran', code: 'GECEC', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Madhepura', code: 'GECMP', state: 'Bihar', category: 'bihar-engineering' },
    { name: 'GEC Bhabua', code: 'GECBH', state: 'Bihar', category: 'bihar-engineering' },

    // ── State Colleges (Major State Universities & Engineering Colleges) ──
    { name: 'Delhi Technological University', code: 'DTU', state: 'Delhi', category: 'state' },
    { name: 'NSUT Delhi', code: 'NSUT', state: 'Delhi', category: 'state' },
    { name: 'IIIT Delhi (State)', code: 'IIITD', state: 'Delhi', category: 'state' },
    { name: 'Jamia Millia Islamia', code: 'JMI', state: 'Delhi', category: 'state' },
    { name: 'JNU Delhi', code: 'JNU', state: 'Delhi', category: 'state' },
    { name: 'Delhi University', code: 'DU', state: 'Delhi', category: 'state' },
    { name: 'Anna University Chennai', code: 'AU', state: 'Tamil Nadu', category: 'state' },
    { name: 'PSG College of Technology', code: 'PSG', state: 'Tamil Nadu', category: 'state' },
    { name: 'College of Engineering Guindy', code: 'CEG', state: 'Tamil Nadu', category: 'state' },
    { name: 'SRM University', code: 'SRM', state: 'Tamil Nadu', category: 'state' },
    { name: 'VIT Vellore', code: 'VIT', state: 'Tamil Nadu', category: 'state' },
    { name: 'BITS Pilani', code: 'BITS', state: 'Rajasthan', category: 'state' },
    { name: 'BITS Hyderabad', code: 'BITSH', state: 'Telangana', category: 'state' },
    { name: 'BITS Goa', code: 'BITSG', state: 'Goa', category: 'state' },
    { name: 'Osmania University', code: 'OU', state: 'Telangana', category: 'state' },
    { name: 'JNTU Hyderabad', code: 'JNTUH', state: 'Telangana', category: 'state' },
    { name: 'University of Hyderabad', code: 'UOH', state: 'Telangana', category: 'state' },
    { name: 'Andhra University', code: 'AU', state: 'Andhra Pradesh', category: 'state' },
    { name: 'JNTU Kakinada', code: 'JNTUK', state: 'Andhra Pradesh', category: 'state' },
    { name: 'Punjab Engineering College Chandigarh', code: 'PEC', state: 'Chandigarh', category: 'state' },
    { name: 'Thapar Institute Patiala', code: 'TIET', state: 'Punjab', category: 'state' },
    { name: 'Punjab University Chandigarh', code: 'PU', state: 'Chandigarh', category: 'state' },
    { name: 'IIT Ropar (State)', code: 'IITRPR', state: 'Punjab', category: 'state' },
    { name: 'GNDU Amritsar', code: 'GNDU', state: 'Punjab', category: 'state' },
    { name: 'COEP Pune', code: 'COEP', state: 'Maharashtra', category: 'state' },
    { name: 'VJTI Mumbai', code: 'VJTI', state: 'Maharashtra', category: 'state' },
    { name: 'Sardar Patel Institute Mumbai', code: 'SPIT', state: 'Maharashtra', category: 'state' },
    { name: 'Pune University (SPPU)', code: 'SPPU', state: 'Maharashtra', category: 'state' },
    { name: 'Mumbai University', code: 'MU', state: 'Maharashtra', category: 'state' },
    { name: 'Fergusson College Pune', code: 'FC', state: 'Maharashtra', category: 'state' },
    { name: 'Jadavpur University', code: 'JU', state: 'West Bengal', category: 'state' },
    { name: 'Calcutta University', code: 'CU', state: 'West Bengal', category: 'state' },
    { name: 'IIEST Shibpur', code: 'IIEST', state: 'West Bengal', category: 'state' },
    { name: 'Heritage Institute Kolkata', code: 'HITK', state: 'West Bengal', category: 'state' },
    { name: 'BMS College Bangalore', code: 'BMSCE', state: 'Karnataka', category: 'state' },
    { name: 'RV College Bangalore', code: 'RVCE', state: 'Karnataka', category: 'state' },
    { name: 'PES University Bangalore', code: 'PESU', state: 'Karnataka', category: 'state' },
    { name: 'Bangalore University', code: 'BU', state: 'Karnataka', category: 'state' },
    { name: 'Mysore University', code: 'MU', state: 'Karnataka', category: 'state' },
    { name: 'NITTE Mangalore', code: 'NITTE', state: 'Karnataka', category: 'state' },
    { name: 'Manipal Institute of Technology', code: 'MITM', state: 'Karnataka', category: 'state' },
    { name: 'Gujarat Technological University', code: 'GTU', state: 'Gujarat', category: 'state' },
    { name: 'Nirma University Ahmedabad', code: 'NU', state: 'Gujarat', category: 'state' },
    { name: 'DA-IICT Gandhinagar', code: 'DAIICT', state: 'Gujarat', category: 'state' },
    { name: 'MS University Baroda', code: 'MSU', state: 'Gujarat', category: 'state' },
    { name: 'Sardar Vallabhbhai Patel Institute', code: 'SVNIT', state: 'Gujarat', category: 'state' },
    { name: 'BITS Mesra Ranchi', code: 'BITM', state: 'Jharkhand', category: 'state' },
    { name: 'Ranchi University', code: 'RU', state: 'Jharkhand', category: 'state' },
    { name: 'Vinoba Bhave University Hazaribagh', code: 'VBU', state: 'Jharkhand', category: 'state' },
    { name: 'KIIT Bhubaneswar', code: 'KIIT', state: 'Odisha', category: 'state' },
    { name: 'SOA Bhubaneswar', code: 'SOA', state: 'Odisha', category: 'state' },
    { name: 'Utkal University', code: 'UU', state: 'Odisha', category: 'state' },
    { name: 'IIT Bhubaneswar (State)', code: 'IITBBS', state: 'Odisha', category: 'state' },
    { name: 'Maulana Azad National Institute Bhopal', code: 'MANIT', state: 'Madhya Pradesh', category: 'state' },
    { name: 'DAVV Indore', code: 'DAVV', state: 'Madhya Pradesh', category: 'state' },
    { name: 'RGPV Bhopal', code: 'RGPV', state: 'Madhya Pradesh', category: 'state' },
    { name: 'LNCT Bhopal', code: 'LNCT', state: 'Madhya Pradesh', category: 'state' },
    { name: 'University of Rajasthan', code: 'UOR', state: 'Rajasthan', category: 'state' },
    { name: 'RTU Kota', code: 'RTU', state: 'Rajasthan', category: 'state' },
    { name: 'LNMIIT Jaipur', code: 'LNMIIT', state: 'Rajasthan', category: 'state' },
    { name: 'Chandigarh University', code: 'CU', state: 'Punjab', category: 'state' },
    { name: 'LPU Jalandhar', code: 'LPU', state: 'Punjab', category: 'state' },
    { name: 'Amity University Noida', code: 'AMITY', state: 'Uttar Pradesh', category: 'state' },
    { name: 'Sharda University Noida', code: 'SHARDA', state: 'Uttar Pradesh', category: 'state' },
    { name: 'AKTU Lucknow', code: 'AKTU', state: 'Uttar Pradesh', category: 'state' },
    { name: 'University of Allahabad', code: 'UOA', state: 'Uttar Pradesh', category: 'state' },
    { name: 'Banaras Hindu University', code: 'BHU', state: 'Uttar Pradesh', category: 'state' },
    { name: 'Aligarh Muslim University', code: 'AMU', state: 'Uttar Pradesh', category: 'state' },
    { name: 'HBTU Kanpur', code: 'HBTU', state: 'Uttar Pradesh', category: 'state' },
    { name: 'IIT Roorkee (State)', code: 'IITR', state: 'Uttarakhand', category: 'state' },
    { name: 'Graphic Era Dehradun', code: 'GEU', state: 'Uttarakhand', category: 'state' },
    { name: 'UPES Dehradun', code: 'UPES', state: 'Uttarakhand', category: 'state' },
    { name: 'Kurukshetra University', code: 'KU', state: 'Haryana', category: 'state' },
    { name: 'YMCA Faridabad', code: 'YMCA', state: 'Haryana', category: 'state' },
    { name: 'NIT Kurukshetra (State)', code: 'NITKKR', state: 'Haryana', category: 'state' },
    { name: 'Panjab University (State)', code: 'PU', state: 'Chandigarh', category: 'state' },
    { name: 'Assam Engineering College Guwahati', code: 'AEC', state: 'Assam', category: 'state' },
    { name: 'Gauhati University', code: 'GU', state: 'Assam', category: 'state' },
    { name: 'Tezpur University', code: 'TU', state: 'Assam', category: 'state' },
    { name: 'IIT Guwahati (State)', code: 'IITG', state: 'Assam', category: 'state' },
    { name: 'Cochin University of Science & Technology', code: 'CUSAT', state: 'Kerala', category: 'state' },
    { name: 'College of Engineering Trivandrum', code: 'CET', state: 'Kerala', category: 'state' },
    { name: 'NIT Calicut (State)', code: 'NITC', state: 'Kerala', category: 'state' },
    { name: 'Kerala University', code: 'KU', state: 'Kerala', category: 'state' },
    { name: 'Panjab Engineering College (State)', code: 'PEC', state: 'Chandigarh', category: 'state' },
    { name: 'NIT Srinagar (State)', code: 'NITSRI', state: 'Jammu & Kashmir', category: 'state' },
    { name: 'University of Kashmir', code: 'UOK', state: 'Jammu & Kashmir', category: 'state' },
    { name: 'NIT Hamirpur (State)', code: 'NITH', state: 'Himachal Pradesh', category: 'state' },
    { name: 'Himachal Pradesh University', code: 'HPU', state: 'Himachal Pradesh', category: 'state' },
    { name: 'NIT Agartala (State)', code: 'NITA', state: 'Tripura', category: 'state' },
    { name: 'Tripura University', code: 'TU', state: 'Tripura', category: 'state' },
    { name: 'NIT Silchar (State)', code: 'NITS', state: 'Assam', category: 'state' },
    { name: 'NIT Meghalaya (State)', code: 'NITM', state: 'Meghalaya', category: 'state' },
    { name: 'NIT Mizoram (State)', code: 'NITMZ', state: 'Mizoram', category: 'state' },
    { name: 'NIT Nagaland (State)', code: 'NITNL', state: 'Nagaland', category: 'state' },
    { name: 'NIT Manipur (State)', code: 'NITMN', state: 'Manipur', category: 'state' },
    { name: 'NIT Arunachal Pradesh (State)', code: 'NITAP', state: 'Arunachal Pradesh', category: 'state' },
    { name: 'NIT Sikkim (State)', code: 'NITSKM', state: 'Sikkim', category: 'state' },
    { name: 'NIT Uttarakhand (State)', code: 'NITUK', state: 'Uttarakhand', category: 'state' },
    { name: 'NIT Goa (State)', code: 'NITGOA', state: 'Goa', category: 'state' },
    { name: 'NIT Delhi (State)', code: 'NITDL', state: 'Delhi', category: 'state' },
    { name: 'NIT Puducherry (State)', code: 'NITPY', state: 'Puducherry', category: 'state' },
    { name: 'NIT Andhra Pradesh (State)', code: 'NITANP', state: 'Andhra Pradesh', category: 'state' },
    { name: 'Goa College of Engineering', code: 'GEC', state: 'Goa', category: 'state' },
    { name: 'Birla Institute of Technology Mesra', code: 'BITM', state: 'Jharkhand', category: 'state' },
    { name: 'National Institute of Foundry & Forge Technology', code: 'NIFFT', state: 'Jharkhand', category: 'state' },
    { name: 'Indian School of Mines Dhanbad', code: 'ISM', state: 'Jharkhand', category: 'state' },
    { name: 'Central University of Jharkhand', code: 'CUJ', state: 'Jharkhand', category: 'state' },
    { name: 'Patna University', code: 'PU', state: 'Bihar', category: 'state' },
    { name: 'Magadh University Bodh Gaya', code: 'MUBG', state: 'Bihar', category: 'state' },
    { name: 'Bihar University Muzaffarpur (B.R.A.B.U.)', code: 'BRABU', state: 'Bihar', category: 'state' },
    { name: 'Tilka Manjhi Bhagalpur University', code: 'TMBU', state: 'Bihar', category: 'state' },
    { name: 'Lalit Narayan Mithila University Darbhanga', code: 'LNMU', state: 'Bihar', category: 'state' },
    { name: 'Jai Prakash University Chapra', code: 'JPU', state: 'Bihar', category: 'state' },
    { name: 'Veer Kunwar Singh University Arrah', code: 'VKSU', state: 'Bihar', category: 'state' },
    { name: 'B.N. Mandal University Madhepura', code: 'BNMU', state: 'Bihar', category: 'state' },
    { name: 'Kameshwar Singh Darbhanga Sanskrit University', code: 'KSDSU', state: 'Bihar', category: 'state' },
    { name: 'Nalanda Open University', code: 'NOU', state: 'Bihar', category: 'state' },
    { name: 'Aryabhatta Knowledge University Patna', code: 'AKU', state: 'Bihar', category: 'state' },
    { name: 'Chanakya National Law University Patna', code: 'CNLU', state: 'Bihar', category: 'state' },
    { name: 'Anugrah Narayan College Patna', code: 'ANC', state: 'Bihar', category: 'state' },
    { name: 'Patna Science College', code: 'PSC', state: 'Bihar', category: 'state' },
    { name: 'Bihar National College Patna', code: 'BNC', state: 'Bihar', category: 'state' },
    { name: 'College of Commerce Patna', code: 'CCP', state: 'Bihar', category: 'state' },
    { name: 'Magadh Mahila College Patna', code: 'MMC', state: 'Bihar', category: 'state' },
    { name: 'Patna Women\'s College', code: 'PWC', state: 'Bihar', category: 'state' },
    { name: 'St. Xavier\'s College Patna', code: 'SXC', state: 'Bihar', category: 'state' },
    { name: 'G.D. College Begusarai', code: 'GDC', state: 'Bihar', category: 'state' },
    { name: 'R.P.S. College Patna', code: 'RPS', state: 'Bihar', category: 'state' },
    { name: 'B.N. College Patna', code: 'BNCP', state: 'Bihar', category: 'state' },
    { name: 'Ram Krishna Dwarika College Patna', code: 'RKD', state: 'Bihar', category: 'state' },
    { name: 'Marwari College Bhagalpur', code: 'MCB', state: 'Bihar', category: 'state' },
    { name: 'T.N.B. College Bhagalpur', code: 'TNB', state: 'Bihar', category: 'state' },
    { name: 'S.M. College Bhagalpur', code: 'SMC', state: 'Bihar', category: 'state' },
    { name: 'Langat Singh College Muzaffarpur', code: 'LSC', state: 'Bihar', category: 'state' },
    { name: 'Ram Dayalu Singh College Muzaffarpur', code: 'RDS', state: 'Bihar', category: 'state' },
    { name: 'C.M. College Darbhanga', code: 'CMC', state: 'Bihar', category: 'state' },
    { name: 'M.L.S. College Darbhanga', code: 'MLS', state: 'Bihar', category: 'state' },
    { name: 'Rajendra College Chapra', code: 'RC', state: 'Bihar', category: 'state' },
    { name: 'D.A.V. College Siwan', code: 'DAV', state: 'Bihar', category: 'state' },
    { name: 'H.D. Jain College Arrah', code: 'HDJ', state: 'Bihar', category: 'state' },
    { name: 'Maharaja College Arrah', code: 'MCA', state: 'Bihar', category: 'state' },
    { name: 'Gaya College Gaya', code: 'GC', state: 'Bihar', category: 'state' },
    { name: 'Anugrah Memorial College Gaya', code: 'AMC', state: 'Bihar', category: 'state' },
    { name: 'S.N. Sinha College Aurangabad', code: 'SNS', state: 'Bihar', category: 'state' },
    { name: 'R.L.S.Y. College Aurangabad', code: 'RLSY', state: 'Bihar', category: 'state' },
    { name: 'J.L.N. College Hajipur', code: 'JLN', state: 'Bihar', category: 'state' },
    { name: 'R.P. Sharma College Hajipur', code: 'RPSH', state: 'Bihar', category: 'state' },
    { name: 'M.S. College Motihari', code: 'MSC', state: 'Bihar', category: 'state' },
    { name: 'B.M. College Rahika', code: 'BMR', state: 'Bihar', category: 'state' },
    { name: 'M.R.M. College Darbhanga', code: 'MRM', state: 'Bihar', category: 'state' },
    { name: 'S.K.M. University Dumka', code: 'SKMU', state: 'Jharkhand', category: 'state' },
    { name: 'Sido Kanhu Murmu University Dumka', code: 'SKMU', state: 'Jharkhand', category: 'state' },
    { name: 'Kolhan University Chaibasa', code: 'KU', state: 'Jharkhand', category: 'state' },
    { name: 'Nilamber Pitamber University Palamu', code: 'NPU', state: 'Jharkhand', category: 'state' },
    { name: 'Jharkhand Raksha Shakti University', code: 'JRSU', state: 'Jharkhand', category: 'state' },
    { name: 'Central University of South Bihar Gaya', code: 'CUSB', state: 'Bihar', category: 'state' },
    { name: 'Nalanda University Rajgir', code: 'NU', state: 'Bihar', category: 'state' },
    { name: 'South Bihar Central University', code: 'SBCU', state: 'Bihar', category: 'state' },
    { name: 'Indian Institute of Management Bodh Gaya (State)', code: 'IIMBG', state: 'Bihar', category: 'state' },
    { name: 'Indian Institute of Technology Patna (State)', code: 'IITP', state: 'Bihar', category: 'state' },
    { name: 'National Institute of Technology Patna (State)', code: 'NITP', state: 'Bihar', category: 'state' },
    { name: 'IIIT Bhagalpur (State)', code: 'IIITBGP', state: 'Bihar', category: 'state' },
    { name: 'AIIMS Patna', code: 'AIIMSP', state: 'Bihar', category: 'state' },
    { name: 'Indira Gandhi Institute of Medical Sciences Patna', code: 'IGIMS', state: 'Bihar', category: 'state' },
    { name: 'Patna Medical College', code: 'PMC', state: 'Bihar', category: 'state' },
    { name: 'Darbhanga Medical College', code: 'DMC', state: 'Bihar', category: 'state' },
    { name: 'Gaya Medical College', code: 'GMC', state: 'Bihar', category: 'state' },
    { name: 'Bhagalpur Medical College', code: 'BMC', state: 'Bihar', category: 'state' },
    { name: 'Muzaffarpur Medical College', code: 'MMC', state: 'Bihar', category: 'state' },
    { name: 'Nalanda Medical College Patna', code: 'NMC', state: 'Bihar', category: 'state' },
    { name: 'Anugrah Narayan Magadh Medical College Gaya', code: 'ANMMC', state: 'Bihar', category: 'state' },
    { name: 'Jawaharlal Nehru Medical College Bhagalpur', code: 'JNMC', state: 'Bihar', category: 'state' },
    { name: 'Sri Krishna Medical College Muzaffarpur', code: 'SKMC', state: 'Bihar', category: 'state' },
    { name: 'Rajendra Memorial Research Institute Patna', code: 'RMRIMS', state: 'Bihar', category: 'state' },
    { name: 'Bihar Agricultural University Sabour', code: 'BAU', state: 'Bihar', category: 'state' },
    { name: 'Dr. Rajendra Prasad Central Agricultural University Pusa', code: 'RPCAU', state: 'Bihar', category: 'state' },
    { name: 'Bihar Veterinary College Patna', code: 'BVC', state: 'Bihar', category: 'state' },
    { name: 'Sanjay Gandhi Institute of Dairy Technology Patna', code: 'SGIDT', state: 'Bihar', category: 'state' },
    { name: 'Bihar Animal Sciences University Patna', code: 'BASU', state: 'Bihar', category: 'state' },
    { name: 'Rajendra Agricultural University Pusa', code: 'RAU', state: 'Bihar', category: 'state' },
    { name: 'Bihar Yoga Bharati Munger', code: 'BYB', state: 'Bihar', category: 'state' },
    { name: 'Nava Nalanda Mahavihara Nalanda', code: 'NNM', state: 'Bihar', category: 'state' },
    { name: 'Central Institute of Buddhist Studies Leh', code: 'CIBS', state: 'Ladakh', category: 'state' },
    { name: 'National Institute of Pharmaceutical Education & Research Hajipur', code: 'NIPERH', state: 'Bihar', category: 'state' },
    { name: 'Bihar Institute of Public Administration & Rural Development', code: 'BIPARD', state: 'Bihar', category: 'state' },
    { name: 'Chandragupt Institute of Management Patna', code: 'CIMP', state: 'Bihar', category: 'state' },
    { name: 'Bihar Institute of Handicrafts & Design', code: 'BIHD', state: 'Bihar', category: 'state' },
    { name: 'National Institute of Technology Jamshedpur (State)', code: 'NITJSR', state: 'Jharkhand', category: 'state' },
    { name: 'Indian Institute of Management Ranchi (State)', code: 'IIMRAN', state: 'Jharkhand', category: 'state' },
    { name: 'Xavier Institute of Social Service Ranchi', code: 'XISS', state: 'Jharkhand', category: 'state' },
    { name: 'St. Xavier\'s College Ranchi', code: 'SXCR', state: 'Jharkhand', category: 'state' },
    { name: 'Ranchi College Ranchi', code: 'RC', state: 'Jharkhand', category: 'state' },
    { name: 'Gossner College Ranchi', code: 'GC', state: 'Jharkhand', category: 'state' },
    { name: 'Marwari College Ranchi', code: 'MCR', state: 'Jharkhand', category: 'state' },
    { name: 'Jamshedpur Women\'s College', code: 'JWC', state: 'Jharkhand', category: 'state' },
    { name: 'Karim City College Jamshedpur', code: 'KCC', state: 'Jharkhand', category: 'state' },
    { name: 'Jamshedpur Co-operative College', code: 'JCC', state: 'Jharkhand', category: 'state' },
    { name: 'Dumka College Dumka', code: 'DC', state: 'Jharkhand', category: 'state' },
    { name: 'S.P. College Dumka', code: 'SPC', state: 'Jharkhand', category: 'state' },
    { name: 'Chaibasa College Chaibasa', code: 'CC', state: 'Jharkhand', category: 'state' },
    { name: 'D.A.V. College Hazaribagh', code: 'DAVH', state: 'Jharkhand', category: 'state' },
    { name: 'Vinoba Bhave University (State)', code: 'VBU', state: 'Jharkhand', category: 'state' },
    { name: 'Central University of Jharkhand (State)', code: 'CUJ', state: 'Jharkhand', category: 'state' },
    { name: 'Indian Institute of Technology Dhanbad (State)', code: 'IITISM', state: 'Jharkhand', category: 'state' },
    { name: 'National Institute of Foundry & Forge Technology (State)', code: 'NIFFT', state: 'Jharkhand', category: 'state' },
    { name: 'Birsa Agricultural University Ranchi', code: 'BAU', state: 'Jharkhand', category: 'state' },
    { name: 'Rajendra Institute of Medical Sciences Ranchi', code: 'RIMS', state: 'Jharkhand', category: 'state' },
    { name: 'M.G.M. Medical College Jamshedpur', code: 'MGM', state: 'Jharkhand', category: 'state' },
    { name: 'Phulo Jhano Medical College Dumka', code: 'PJMC', state: 'Jharkhand', category: 'state' },
    { name: 'Hazaribagh Medical College', code: 'HMC', state: 'Jharkhand', category: 'state' },
    { name: 'Shaheed Nirmal Mahto Medical College Dhanbad', code: 'SNMMC', state: 'Jharkhand', category: 'state' },
    { name: 'Jharkhand University of Technology Ranchi', code: 'JUT', state: 'Jharkhand', category: 'state' },
    { name: 'Cambridge Institute of Technology Ranchi', code: 'CIT', state: 'Jharkhand', category: 'state' },
    { name: 'Arka Jain University Jamshedpur', code: 'AJU', state: 'Jharkhand', category: 'state' },
    { name: 'Netaji Subhas University Jamshedpur', code: 'NSU', state: 'Jharkhand', category: 'state' },
    { name: 'Sai Nath University Ranchi', code: 'SNU', state: 'Jharkhand', category: 'state' },
    { name: 'Usha Martin University Ranchi', code: 'UMU', state: 'Jharkhand', category: 'state' },
    { name: 'Radha Govind University Ramgarh', code: 'RGU', state: 'Jharkhand', category: 'state' },
    { name: 'Binod Bihari Mahto Koyalanchal University Dhanbad', code: 'BBMKU', state: 'Jharkhand', category: 'state' },
    { name: 'Dr. Shyama Prasad Mukherjee University Ranchi', code: 'DSPMU', state: 'Jharkhand', category: 'state' },
    { name: 'Central University of South Bihar (State)', code: 'CUSB', state: 'Bihar', category: 'state' },
    { name: 'Nalanda University (State)', code: 'NU', state: 'Bihar', category: 'state' },
    { name: 'South Bihar Central University (State)', code: 'SBCU', state: 'Bihar', category: 'state' },
    { name: 'Indian Institute of Management Bodh Gaya (State)', code: 'IIMBG', state: 'Bihar', category: 'state' },
    { name: 'Indian Institute of Technology Patna (State)', code: 'IITP', state: 'Bihar', category: 'state' },
    { name: 'National Institute of Technology Patna (State)', code: 'NITP', state: 'Bihar', category: 'state' },
    { name: 'IIIT Bhagalpur (State)', code: 'IIITBGP', state: 'Bihar', category: 'state' },
    { name: 'AIIMS Patna (State)', code: 'AIIMSP', state: 'Bihar', category: 'state' },
    { name: 'Indira Gandhi Institute of Medical Sciences Patna (State)', code: 'IGIMS', state: 'Bihar', category: 'state' },
    { name: 'Patna Medical College (State)', code: 'PMC', state: 'Bihar', category: 'state' },
    { name: 'Darbhanga Medical College (State)', code: 'DMC', state: 'Bihar', category: 'state' },
    { name: 'Gaya Medical College (State)', code: 'GMC', state: 'Bihar', category: 'state' },
    { name: 'Bhagalpur Medical College (State)', code: 'BMC', state: 'Bihar', category: 'state' },
    { name: 'Muzaffarpur Medical College (State)', code: 'MMC', state: 'Bihar', category: 'state' },
    { name: 'Nalanda Medical College Patna (State)', code: 'NMC', state: 'Bihar', category: 'state' },
    { name: 'Anugrah Narayan Magadh Medical College Gaya (State)', code: 'ANMMC', state: 'Bihar', category: 'state' },
    { name: 'Jawaharlal Nehru Medical College Bhagalpur (State)', code: 'JNMC', state: 'Bihar', category: 'state' },
    { name: 'Sri Krishna Medical College Muzaffarpur (State)', code: 'SKMC', state: 'Bihar', category: 'state' },
    { name: 'Rajendra Memorial Research Institute Patna (State)', code: 'RMRIMS', state: 'Bihar', category: 'state' },
    { name: 'Bihar Agricultural University Sabour (State)', code: 'BAU', state: 'Bihar', category: 'state' },
    { name: 'Dr. Rajendra Prasad Central Agricultural University Pusa (State)', code: 'RPCAU', state: 'Bihar', category: 'state' },
    { name: 'Bihar Veterinary College Patna (State)', code: 'BVC', state: 'Bihar', category: 'state' },
    { name: 'Sanjay Gandhi Institute of Dairy Technology Patna (State)', code: 'SGIDT', state: 'Bihar', category: 'state' },
    { name: 'Bihar Animal Sciences University Patna (State)', code: 'BASU', state: 'Bihar', category: 'state' },
    { name: 'Rajendra Agricultural University Pusa (State)', code: 'RAU', state: 'Bihar', category: 'state' },
    { name: 'Bihar Yoga Bharati Munger (State)', code: 'BYB', state: 'Bihar', category: 'state' },
    { name: 'Nava Nalanda Mahavihara Nalanda (State)', code: 'NNM', state: 'Bihar', category: 'state' },
    { name: 'National Institute of Pharmaceutical Education & Research Hajipur (State)', code: 'NIPERH', state: 'Bihar', category: 'state' },
    { name: 'Bihar Institute of Public Administration & Rural Development (State)', code: 'BIPARD', state: 'Bihar', category: 'state' },
    { name: 'Chandragupt Institute of Management Patna (State)', code: 'CIMP', state: 'Bihar', category: 'state' },
    { name: 'Bihar Institute of Handicrafts & Design (State)', code: 'BIHD', state: 'Bihar', category: 'state' },
    { name: 'National Institute of Technology Jamshedpur (State)', code: 'NITJSR', state: 'Jharkhand', category: 'state' },
    { name: 'Indian Institute of Management Ranchi (State)', code: 'IIMRAN', state: 'Jharkhand', category: 'state' },
    { name: 'Xavier Institute of Social Service Ranchi (State)', code: 'XISS', state: 'Jharkhand', category: 'state' },
    { name: 'St. Xavier\'s College Ranchi (State)', code: 'SXCR', state: 'Jharkhand', category: 'state' },
    { name: 'Ranchi College Ranchi (State)', code: 'RC', state: 'Jharkhand', category: 'state' },
    { name: 'Gossner College Ranchi (State)', code: 'GC', state: 'Jharkhand', category: 'state' },
    { name: 'Marwari College Ranchi (State)', code: 'MCR', state: 'Jharkhand', category: 'state' },
    { name: 'Jamshedpur Women\'s College (State)', code: 'JWC', state: 'Jharkhand', category: 'state' },
    { name: 'Karim City College Jamshedpur (State)', code: 'KCC', state: 'Jharkhand', category: 'state' },
    { name: 'Jamshedpur Co-operative College (State)', code: 'JCC', state: 'Jharkhand', category: 'state' },
    { name: 'Dumka College Dumka (State)', code: 'DC', state: 'Jharkhand', category: 'state' },
    { name: 'S.P. College Dumka (State)', code: 'SPC', state: 'Jharkhand', category: 'state' },
    { name: 'Chaibasa College Chaibasa (State)', code: 'CC', state: 'Jharkhand', category: 'state' },
    { name: 'D.A.V. College Hazaribagh (State)', code: 'DAVH', state: 'Jharkhand', category: 'state' },
    { name: 'Vinoba Bhave University (State)', code: 'VBU', state: 'Jharkhand', category: 'state' },
    { name: 'Central University of Jharkhand (State)', code: 'CUJ', state: 'Jharkhand', category: 'state' },
    { name: 'Indian Institute of Technology Dhanbad (State)', code: 'IITISM', state: 'Jharkhand', category: 'state' },
    { name: 'National Institute of Foundry & Forge Technology (State)', code: 'NIFFT', state: 'Jharkhand', category: 'state' },
    { name: 'Birsa Agricultural University Ranchi (State)', code: 'BAU', state: 'Jharkhand', category: 'state' },
    { name: 'Rajendra Institute of Medical Sciences Ranchi (State)', code: 'RIMS', state: 'Jharkhand', category: 'state' },
    { name: 'M.G.M. Medical College Jamshedpur (State)', code: 'MGM', state: 'Jharkhand', category: 'state' },
    { name: 'Phulo Jhano Medical College Dumka (State)', code: 'PJMC', state: 'Jharkhand', category: 'state' },
    { name: 'Hazaribagh Medical College (State)', code: 'HMC', state: 'Jharkhand', category: 'state' },
    { name: 'Shaheed Nirmal Mahto Medical College Dhanbad (State)', code: 'SNMMC', state: 'Jharkhand', category: 'state' },
    { name: 'Jharkhand University of Technology Ranchi (State)', code: 'JUT', state: 'Jharkhand', category: 'state' },
    { name: 'Cambridge Institute of Technology Ranchi (State)', code: 'CIT', state: 'Jharkhand', category: 'state' },
    { name: 'Arka Jain University Jamshedpur (State)', code: 'AJU', state: 'Jharkhand', category: 'state' },
    { name: 'Netaji Subhas University Jamshedpur (State)', code: 'NSU', state: 'Jharkhand', category: 'state' },
    { name: 'Sai Nath University Ranchi (State)', code: 'SNU', state: 'Jharkhand', category: 'state' },
    { name: 'Usha Martin University Ranchi (State)', code: 'UMU', state: 'Jharkhand', category: 'state' },
    { name: 'Radha Govind University Ramgarh (State)', code: 'RGU', state: 'Jharkhand', category: 'state' },
    { name: 'Binod Bihari Mahto Koyalanchal University Dhanbad (State)', code: 'BBMKU', state: 'Jharkhand', category: 'state' },
    { name: 'Dr. Shyama Prasad Mukherjee University Ranchi (State)', code: 'DSPMU', state: 'Jharkhand', category: 'state' },
];

// Helper functions
export const getCollegesByCategory = (category: College['category']) =>
    COLLEGES.filter((c) => c.category === category);

export const getCollegesByState = (state: string) =>
    COLLEGES.filter((c) => c.state.toLowerCase() === state.toLowerCase());

export const searchColleges = (query: string) => {
    const q = query.toLowerCase().trim();
    if (!q) return COLLEGES;
    return COLLEGES.filter(
        (c) =>
            c.name.toLowerCase().includes(q) ||
            c.code.toLowerCase().includes(q) ||
            c.state.toLowerCase().includes(q)
    );
};

export const getCollegeByCode = (code: string) =>
    COLLEGES.find((c) => c.code.toLowerCase() === code.toLowerCase());