"use client";

/**
 * E2EEContext — Manages per-session E2EE key material and exposes
 * encrypt/decrypt helpers to the chat page.
 *
 * Key lifecycle:
 *  - ECDH key pair is generated fresh on mount (ephemeral per page load)
 *  - Public key is published to the server REST API so peers can wrap room keys for us
 *  - Room key is generated by this client; on each message send it is wrapped
 *    individually for every current member's active devices (Sender Key pattern)
 *  - When a peer joins they broadcast their public key + deviceId via socket;
 *    we immediately wrap our current room key for them
 *  - When we join we broadcast our public key + deviceId; an existing member wraps
 *    their room key for us → we can decrypt subsequent messages
 */

import React, {
  createContext,
  useContext,
  useEffect,
  useRef,
  useState,
  useCallback,
} from 'react';
import * as e2ee from '@/lib/e2ee';
import API from '@/lib/axios';
import { useSocket } from './SocketContext';
import { useAuth } from './authContext';
import { Message } from '@/lib/types';

// Helper to get or create a unique device/session ID for this browser tab/instance
const getOrCreateDeviceId = (): string => {
  if (typeof window === 'undefined') return 'default';
  let id = localStorage.getItem('deviceId');
  if (!id) {
    id = typeof crypto.randomUUID === 'function'
      ? crypto.randomUUID()
      : Math.random().toString(36).substring(2) + Date.now().toString(36);
    localStorage.setItem('deviceId', id);
  }
  return id;
};

// ── Types ─────────────────────────────────────────────────────────────────────

export interface EncryptedPayload {
  ciphertext: string;
  iv: string;
  encryptedKeys: Record<string, string>; // { [deviceId]: base64WrappedRoomKey }
}

interface E2EEContextValue {
  /** true once key pair is generated and public key published to server */
  isReady: boolean;
  /**
   * Encrypt a plaintext message for all memberIds.
   * Fetches any missing public keys from the REST API on-demand.
   */
  encrypt: (text: string, memberIds: string[]) => Promise<EncryptedPayload | null>;
  /**
   * Decrypt an incoming Message. Returns the plaintext, or a safe fallback
   * string if keys are unavailable or decryption fails.
   */
  decrypt: (msg: Message) => Promise<string>;
  /**
   * Announce our public key to the session room so peers can distribute
   * room keys to us. Call this after emitting joinSession.
   */
  announcePublicKey: (sessionId: string) => void;
}

// ── Context ───────────────────────────────────────────────────────────────────

const E2EEContext = createContext<E2EEContextValue | null>(null);

export const useE2EE = () => useContext(E2EEContext);

// ── Provider ──────────────────────────────────────────────────────────────────

export function E2EEProvider({ children }: { children: React.ReactNode }) {
  const { socket } = useSocket() as any;
  const { userId } = useAuth() as any;

  // Refs — mutations don't cause re-renders
  const keyPairRef = useRef<CryptoKeyPair | null>(null);
  const publicKeyB64Ref = useRef<string | null>(null);
  const memberKeysRef = useRef<Map<string, CryptoKey>>(new Map()); // deviceId -> CryptoKey
  const memberDevicesRef = useRef<Map<string, string[]>>(new Map()); // userId -> deviceIds[]
  const roomKeyRef = useRef<CryptoKey | null>(null);

  const [isReady, setIsReady] = useState(false);

  // ── Phase 1: Load or generate key pair + room key on mount ─────────────────
  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const kp = await e2ee.loadOrGenerateKeyPair();
        const pubB64 = await e2ee.exportPublicKey(kp.publicKey);
        const rk = await e2ee.generateRoomKey();

        if (cancelled) return;

        keyPairRef.current = kp;
        publicKeyB64Ref.current = pubB64;
        roomKeyRef.current = rk;

        setIsReady(true);

        // Publish public key + deviceId to server (best-effort, non-blocking).
        const deviceId = getOrCreateDeviceId();
        API.put('/auth/public-key', { publicKey: pubB64, deviceId }).catch((err: unknown) => {
          console.warn('[E2EE] Could not publish public key to server (non-fatal):', (err as any)?.message ?? err);
        });
      } catch (err) {
        console.error('[E2EE] Key generation failed:', err);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  // ── Phase 2: Socket-based key exchange ────────────────────────────────────────
  useEffect(() => {
    if (!socket || !isReady) return;

    /**
     * A peer joined the session and announced their public key.
     * We import their key and immediately send them our current room key.
     */
    const onMemberJoined = async (data: {
      userId: string;
      publicKey: string;
      sessionId: string;
      deviceId: string;
    }) => {
      if (data.userId === userId) return; // ignore our own announce

      try {
        const memberPubKey = await e2ee.importPublicKey(data.publicKey);
        memberKeysRef.current.set(data.deviceId, memberPubKey);

        // Track this deviceId for this user
        const currentDevs = memberDevicesRef.current.get(data.userId) || [];
        if (!currentDevs.includes(data.deviceId)) {
          memberDevicesRef.current.set(data.userId, [...currentDevs, data.deviceId]);
        }

        // Distribute our room key to the new member's device (they need it to decrypt)
        if (roomKeyRef.current && socket) {
          const wrapped = await e2ee.encryptRoomKeyForMember(roomKeyRef.current, memberPubKey);
          socket.emit('e2ee:keyPackage', {
            sessionId: data.sessionId,
            toUserId: data.userId,
            toDeviceId: data.deviceId,
            encryptedRoomKey: wrapped,
          });
        }
      } catch (err) {
        console.warn('[E2EE] onMemberJoined error:', err);
      }
    };

    /**
     * An existing member sent us their room key (in response to our announce).
     * We import it so we can decrypt their messages.
     */
    const onKeyPackage = async (data: {
      fromUserId: string;
      toDeviceId: string;
      encryptedRoomKey: string;
    }) => {
      if (!keyPairRef.current) return;

      const myDeviceId = getOrCreateDeviceId();
      // Ignore key packages meant for other devices/tabs
      if (data.toDeviceId !== myDeviceId) return;

      try {
        const rk = await e2ee.decryptRoomKey(
          data.encryptedRoomKey,
          keyPairRef.current.privateKey,
        );
        // Accept the first valid room key we receive
        if (!roomKeyRef.current) {
          roomKeyRef.current = rk;
        }
      } catch (err) {
        console.warn('[E2EE] Room key decryption failed from', data.fromUserId, ':', err);
      }
    };

    socket.on('e2ee:memberJoined', onMemberJoined);
    socket.on('e2ee:keyPackage', onKeyPackage);

    return () => {
      socket.off('e2ee:memberJoined', onMemberJoined);
      socket.off('e2ee:keyPackage', onKeyPackage);
    };
  }, [socket, isReady, userId]);

  // ── Public API ────────────────────────────────────────────────────────────────

  const announcePublicKey = useCallback(
    (sessionId: string) => {
      if (!socket || !publicKeyB64Ref.current) return;
      const deviceId = getOrCreateDeviceId();
      socket.emit('e2ee:announce', {
        sessionId,
        publicKey: publicKeyB64Ref.current,
        deviceId,
      });
    },
    [socket],
  );

  const encrypt = useCallback(
    async (text: string, memberIds: string[]): Promise<EncryptedPayload | null> => {
      if (!roomKeyRef.current) return null;

      // Encrypt the message body
      const { iv, ciphertext } = await e2ee.encryptMessage(text, roomKeyRef.current);

      // Check which members we are missing device public keys for
      const missingIds = memberIds.filter((id) => {
        if (id === userId) return false;
        const devs = memberDevicesRef.current.get(id);
        return !devs || devs.length === 0;
      });

      if (missingIds.length > 0) {
        try {
          const res = await API.get(`/auth/public-keys?userIds=${missingIds.join(',')}`);
          const keys = res.data.keys as Record<string, { deviceId: string; publicKey: string }[]>;
          
          for (const [uid, deviceList] of Object.entries(keys)) {
            const devIds: string[] = [];
            for (const dev of deviceList) {
              devIds.push(dev.deviceId);
              if (!memberKeysRef.current.has(dev.deviceId)) {
                const pk = await e2ee.importPublicKey(dev.publicKey);
                memberKeysRef.current.set(dev.deviceId, pk);
              }
            }
            memberDevicesRef.current.set(uid, devIds);
          }
        } catch (err) {
          console.warn('[E2EE] Failed to fetch member public keys:', err);
        }
      }

      // Wrap room key for each active device of each member (+ ourselves so we can decrypt our own history)
      const encryptedKeys: Record<string, string> = {};
      const allIds = [...new Set([...memberIds, userId])].filter(Boolean);
      const myDeviceId = getOrCreateDeviceId();

      for (const memberId of allIds) {
        if (memberId === userId) {
          if (keyPairRef.current) {
            try {
              encryptedKeys[myDeviceId] = await e2ee.encryptRoomKeyForMember(
                roomKeyRef.current,
                keyPairRef.current.publicKey,
              );
            } catch (err) {
              console.warn('[E2EE] Failed to wrap key for self:', err);
            }
          }
        } else {
          const deviceIds = memberDevicesRef.current.get(memberId) || [];
          for (const devId of deviceIds) {
            const devicePubKey = memberKeysRef.current.get(devId);
            if (devicePubKey) {
              try {
                encryptedKeys[devId] = await e2ee.encryptRoomKeyForMember(
                  roomKeyRef.current,
                  devicePubKey,
                );
              } catch (err) {
                console.warn('[E2EE] Failed to wrap key for device', devId, ':', err);
              }
            }
          }
        }
      }

      return { ciphertext, iv, encryptedKeys };
    },
    [userId],
  );

  const decrypt = useCallback(
    async (msg: Message): Promise<string> => {
      if (!msg.ciphertext || !msg.iv || !msg.encryptedKeys) return msg.text;

      let encryptedKeys = msg.encryptedKeys;
      if (typeof encryptedKeys === 'string') {
        try {
          encryptedKeys = JSON.parse(encryptedKeys);
        } catch {
          console.error('[E2EE][decrypt] encryptedKeys is not valid JSON:', encryptedKeys);
          return '__E2EE_ERR__KEY_MISMATCH';
        }
      }

      if (!keyPairRef.current) {
        console.warn('[E2EE][decrypt] keyPairRef is null — keys not ready yet');
        return '__E2EE_ERR__KEYS_NOT_READY';
      }

      const myDeviceId = getOrCreateDeviceId();
      // Try to find key packaged for this device session first; fall back to userId for legacy messages
      const myWrappedKey = encryptedKeys[myDeviceId] || encryptedKeys[userId];

      if (!myWrappedKey) {
        console.warn(
          '[E2EE][decrypt] No wrapped key found for current device/user.\n',
          '  My deviceId:', myDeviceId, '\n',
          '  My userId:', userId, '\n',
          '  Keys in message:', Object.keys(encryptedKeys),
        );
        return '__E2EE_ERR__NOT_RECIPIENT';
      }

      try {
        const rk = await e2ee.decryptRoomKey(myWrappedKey, keyPairRef.current.privateKey);
        return await e2ee.decryptMessage(msg.iv, msg.ciphertext, rk);
      } catch (err) {
        console.error(
          '[E2EE][decrypt] Crypto error — private key does not match the public key\n',
          '  msg.id:', msg.id, '\n',
          '  err:', err,
        );
        return '__E2EE_ERR__KEY_MISMATCH';
      }
    },
    [userId],
  );

  return (
    <E2EEContext.Provider value={{ isReady, encrypt, decrypt, announcePublicKey }}>
      {children}
    </E2EEContext.Provider>
  );
}

