"use client";

/**
 * E2EEContext — Manages per-session E2EE key material and exposes
 * encrypt/decrypt helpers to the chat page.
 *
 * Key lifecycle:
 *  - ECDH key pair is generated fresh on mount (ephemeral per page load)
 *  - Public key is published to the server REST API so peers can wrap room keys for us
 *  - Room key is generated by this client; on each message send it is wrapped
 *    individually for every current member (Sender Key pattern)
 *  - When a peer joins they broadcast their public key via socket;
 *    we immediately wrap our current room key for them
 *  - When we join we broadcast our public key; an existing member wraps
 *    their room key for us → we can decrypt subsequent messages
 */

import React, {
  createContext,
  useContext,
  useEffect,
  useRef,
  useState,
  useCallback,
} from 'react';
import * as e2ee from '@/lib/e2ee';
import API from '@/lib/axios';
import { useSocket } from './SocketContext';
import { useAuth } from './authContext';
import { Message } from '@/lib/types';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface EncryptedPayload {
  ciphertext: string;
  iv: string;
  encryptedKeys: Record<string, string>; // { [userId]: base64WrappedRoomKey }
}

interface E2EEContextValue {
  /** true once key pair is generated and public key published to server */
  isReady: boolean;
  /**
   * Encrypt a plaintext message for all memberIds.
   * Fetches any missing public keys from the REST API on-demand.
   */
  encrypt: (text: string, memberIds: string[]) => Promise<EncryptedPayload | null>;
  /**
   * Decrypt an incoming Message. Returns the plaintext, or a safe fallback
   * string if keys are unavailable or decryption fails.
   */
  decrypt: (msg: Message) => Promise<string>;
  /**
   * Announce our public key to the session room so peers can distribute
   * room keys to us. Call this after emitting joinSession.
   */
  announcePublicKey: (sessionId: string) => void;
}

// ── Context ───────────────────────────────────────────────────────────────────

const E2EEContext = createContext<E2EEContextValue | null>(null);

export const useE2EE = () => useContext(E2EEContext);

// ── Provider ──────────────────────────────────────────────────────────────────

export function E2EEProvider({ children }: { children: React.ReactNode }) {
  const { socket } = useSocket() as any;
  const { userId } = useAuth() as any;

  // Refs — mutations don't cause re-renders
  const keyPairRef = useRef<CryptoKeyPair | null>(null);
  const publicKeyB64Ref = useRef<string | null>(null);
  const memberKeysRef = useRef<Map<string, CryptoKey>>(new Map());
  const roomKeyRef = useRef<CryptoKey | null>(null);

  const [isReady, setIsReady] = useState(false);

  // ── Phase 1: Load or generate key pair + room key on mount ─────────────────
  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        // loadOrGenerateKeyPair persists the ECDH key pair in IndexedDB.
        // On refresh, the SAME private key is reused so historical messages
        // (whose wrappedRoomKeys were encrypted to this public key) can still
        // be decrypted. Falls back to ephemeral if IndexedDB is unavailable.
        const kp = await e2ee.loadOrGenerateKeyPair();
        const pubB64 = await e2ee.exportPublicKey(kp.publicKey);
        const rk = await e2ee.generateRoomKey();

        if (cancelled) return;

        keyPairRef.current = kp;
        publicKeyB64Ref.current = pubB64;
        roomKeyRef.current = rk;

        // Mark E2EE as ready immediately — crypto is ready regardless of server state
        setIsReady(true);

        // Publish public key to server (best-effort, non-blocking).
        // Used for REST-based key fetching; socket-based exchange works without it.
        API.put('/auth/public-key', { publicKey: pubB64 }).catch((err: unknown) => {
          console.warn('[E2EE] Could not publish public key to server (non-fatal):', (err as any)?.message ?? err);
        });
      } catch (err) {
        console.error('[E2EE] Key generation failed:', err);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  // ── Phase 2: Socket-based key exchange ────────────────────────────────────────
  useEffect(() => {
    if (!socket || !isReady) return;

    /**
     * A peer joined the session and announced their public key.
     * We import their key and immediately send them our current room key.
     */
    const onMemberJoined = async (data: {
      userId: string;
      publicKey: string;
      sessionId: string;
    }) => {
      if (data.userId === userId) return; // ignore our own announce

      try {
        const memberPubKey = await e2ee.importPublicKey(data.publicKey);
        memberKeysRef.current.set(data.userId, memberPubKey);

        // Distribute our room key to the new member (they need it to decrypt)
        if (roomKeyRef.current && socket) {
          const wrapped = await e2ee.encryptRoomKeyForMember(roomKeyRef.current, memberPubKey);
          socket.emit('e2ee:keyPackage', {
            sessionId: data.sessionId,
            toUserId: data.userId,
            encryptedRoomKey: wrapped,
          });
        }
      } catch (err) {
        console.warn('[E2EE] onMemberJoined error:', err);
      }
    };

    /**
     * An existing member sent us their room key (in response to our announce).
     * We import it so we can decrypt their messages.
     */
    const onKeyPackage = async (data: {
      fromUserId: string;
      encryptedRoomKey: string;
    }) => {
      if (!keyPairRef.current) return;

      try {
        const rk = await e2ee.decryptRoomKey(
          data.encryptedRoomKey,
          keyPairRef.current.privateKey,
        );
        // Accept the first valid room key we receive
        if (!roomKeyRef.current) {
          roomKeyRef.current = rk;
        }
        // Also store separately keyed to sender if we want per-sender keys later
      } catch (err) {
        console.warn('[E2EE] Room key decryption failed from', data.fromUserId, ':', err);
      }
    };

    /**
     * Server broadcast: a member's public key (used to pre-populate memberKeys
     * when the server relays existing members' keys to a new joiner).
     */
    const onMemberPublicKey = async (data: { userId: string; publicKey: string }) => {
      try {
        const pk = await e2ee.importPublicKey(data.publicKey);
        memberKeysRef.current.set(data.userId, pk);
      } catch {}
    };

    socket.on('e2ee:memberJoined', onMemberJoined);
    socket.on('e2ee:keyPackage', onKeyPackage);
    socket.on('e2ee:memberPublicKey', onMemberPublicKey);

    return () => {
      socket.off('e2ee:memberJoined', onMemberJoined);
      socket.off('e2ee:keyPackage', onKeyPackage);
      socket.off('e2ee:memberPublicKey', onMemberPublicKey);
    };
  }, [socket, isReady, userId]);

  // ── Public API ────────────────────────────────────────────────────────────────

  const announcePublicKey = useCallback(
    (sessionId: string) => {
      if (!socket || !publicKeyB64Ref.current) return;
      socket.emit('e2ee:announce', {
        sessionId,
        publicKey: publicKeyB64Ref.current,
      });
    },
    [socket],
  );

  const encrypt = useCallback(
    async (text: string, memberIds: string[]): Promise<EncryptedPayload | null> => {
      if (!roomKeyRef.current) return null;

      // Encrypt the message body
      const { iv, ciphertext } = await e2ee.encryptMessage(text, roomKeyRef.current);

      // Collect member public keys — fetch missing ones from REST
      const missingIds = memberIds.filter(
        (id) => id !== userId && !memberKeysRef.current.has(id),
      );

      if (missingIds.length > 0) {
        try {
          const res = await API.get(`/auth/public-keys?userIds=${missingIds.join(',')}`);
          const keys = res.data.keys as Record<string, string>;
          for (const [uid, pubB64] of Object.entries(keys)) {
            const pk = await e2ee.importPublicKey(pubB64);
            memberKeysRef.current.set(uid, pk);
          }
        } catch (err) {
          console.warn('[E2EE] Failed to fetch member public keys:', err);
        }
      }

      // Wrap room key for each member (+ ourselves so we can decrypt our own history)
      const encryptedKeys: Record<string, string> = {};

      const allIds = [...new Set([...memberIds, userId])].filter(Boolean);
      for (const memberId of allIds) {
        let memberPubKey: CryptoKey | undefined;

        if (memberId === userId && keyPairRef.current) {
          // Wrap for self using our own public key
          memberPubKey = keyPairRef.current.publicKey;
        } else {
          memberPubKey = memberKeysRef.current.get(memberId);
        }

        if (memberPubKey) {
          try {
            encryptedKeys[memberId] = await e2ee.encryptRoomKeyForMember(
              roomKeyRef.current,
              memberPubKey,
            );
          } catch (err) {
            console.warn('[E2EE] Failed to wrap key for', memberId, ':', err);
          }
        }
      }

      return { ciphertext, iv, encryptedKeys };
    },
    [userId],
  );

  const decrypt = useCallback(
    async (msg: Message): Promise<string> => {
      // Not an encrypted message — return plaintext as-is
      if (!msg.ciphertext || !msg.iv || !msg.encryptedKeys) return msg.text;

      // Defensive: if encryptedKeys arrived as a JSON string instead of an object, parse it
      let encryptedKeys = msg.encryptedKeys;
      if (typeof encryptedKeys === 'string') {
        try { encryptedKeys = JSON.parse(encryptedKeys); }
        catch { console.error('[E2EE][decrypt] encryptedKeys is not valid JSON:', encryptedKeys); return '__E2EE_ERR__KEY_MISMATCH'; }
      }

      if (!keyPairRef.current) {
        console.warn('[E2EE][decrypt] keyPairRef is null — keys not ready yet');
        return '__E2EE_ERR__KEYS_NOT_READY';
      }

      const myWrappedKey = encryptedKeys[userId];

      if (!myWrappedKey) {
        console.warn(
          '[E2EE][decrypt] No wrapped key found for current user.\n',
          '  My userId:', userId, '\n',
          '  Keys in message (recipient userIds):', Object.keys(encryptedKeys),
        );
        return '__E2EE_ERR__NOT_RECIPIENT';
      }

      try {
        const rk = await e2ee.decryptRoomKey(myWrappedKey, keyPairRef.current.privateKey);
        return await e2ee.decryptMessage(msg.iv, msg.ciphertext, rk);
      } catch (err) {
        console.error(
          '[E2EE][decrypt] Crypto error — private key does not match the public key\n',
          '  used when this message was encrypted (pre-persistence or key rotation).\n',
          '  msg.id:', msg.id, '\n',
          '  err:', err,
        );
        return '__E2EE_ERR__KEY_MISMATCH';
      }
    },
    [userId],
  );

  return (
    <E2EEContext.Provider value={{ isReady, encrypt, decrypt, announcePublicKey }}>
      {children}
    </E2EEContext.Provider>
  );
}
